version: '3.7'
services:
  db:
    container_name: postgres
    image: postgres:16
    restart: always
    env_file:
      - .env.development
    environment:
      PG_DATA: /var/lib/postgresql@16/data
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql@16/data
volumes:
  db: